basecache: &basecache
  namespace: "apiconfig"
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 30
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 30
  ingress: &ingress
    create: true
    host: "weudev.apiconfig.internal.dev.platform.pagopa.it"
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.25"
    limits:
      memory: "6G"
      cpu: "2.5"
  envConfig: &envConfig
    AZURE_INSIGHTS_ENABLED: "true"
    REDIS_HOST: "pagopa-d-redis.redis.cache.windows.net"
    REDIS_PORT: "6380"
  secretProvider: &azureSecretProvider
    create: true
    envSecrets: &envSecret
      APPLICATIONINSIGHTS_CONNECTION_STRING: "ai-d-connection-string"
      REDIS_PWD: "redis-password"
    keyvault:
      name: "pagopa-d-apiconfig-kv"
      tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  tmpVolumeMount:
    create: true
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
# Configuration used to update image tag
postgresql:
  !!merge <<: *basecache
  image:
    repository: pagopadcommonacr.azurecr.io/pagopaapiconfigcache
    tag: "0.6.0"
  ingress:
    !!merge <<: *ingress
    path: /api-config-cache/p(/|$)(.*)
  envConfig:
    !!merge <<: *envConfig
    APPLICATIONINSIGHTS_ROLE_NAME: "pagopa-api-config-cache-postgresql"
    DB_CONFIG_URL: "jdbc:postgresql://ndp.d.db-nodo-pagamenti.com:6432/nodo?sslmode=require&prepareThreshold=0&currentSchema=cfg"
    DB_CONFIG_USER: "cfg"
    DB_CONFIG_DRIVER: "org.postgresql.Driver"
    DATABASE_ID: "p"
    HEALTHCHECK_QUERY: "select 1"
    SAVE_DB: "true"
  secretProvider:
    !!merge <<: *azureSecretProvider
    envSecrets:
      !!merge <<: *envSecret
      DB_CONFIG_PASSWORD: "postgresql-db-cfg-password"
oracle:
  !!merge <<: *basecache
  image:
    repository: pagopadcommonacr.azurecr.io/pagopaapiconfigcache
    tag: "0.6.0"
  ingress:
    !!merge <<: *ingress
    path: /api-config-cache/o(/|$)(.*)
  envConfig:
    !!merge <<: *envConfig
    APPLICATIONINSIGHTS_ROLE_NAME: "pagopa-api-config-cache-oracle"
    DB_CONFIG_URL: "jdbc:oracle:thin:@db-nodo-pagamenti.d.db-nodo-pagamenti.com:1522/NDPSPCT_PP_NODO4_CFG"
    DB_CONFIG_USER: "NODO4_CFG"
    DB_CONFIG_DRIVER: "oracle.jdbc.OracleDriver"
    JAVA_OPTS: "-Dspring.jpa.show-sql=false"
    DATABASE_ID: "o"
    HEALTHCHECK_QUERY: "select 1 from dual"
    SAVE_DB: "true"
  secretProvider:
    !!merge <<: *azureSecretProvider
    envSecrets:
      !!merge <<: *envSecret
      DB_CONFIG_PASSWORD: "oracle-db-cfg-password"
oracledev:
  !!merge <<: *basecache
  image:
    repository: pagopadcommonacr.azurecr.io/pagopaapiconfigcache
    tag: "0.6.0"
  ingress:
    !!merge <<: *ingress
    path: /api-config-cachedev/o(/|$)(.*)
  envConfig:
    !!merge <<: *envConfig
    APPLICATIONINSIGHTS_ROLE_NAME: "pagopa-api-config-cache-oracle"
    DB_CONFIG_URL: "jdbc:oracle:thin:@db-nodo-pagamenti.d.db-nodo-pagamenti.com:1522/NDPSPCT_NODO4_CFG"
    DB_CONFIG_USER: "NODO4_CFG_DEV"
    DB_CONFIG_DRIVER: "oracle.jdbc.OracleDriver"
    JAVA_OPTS: "-Dspring.jpa.show-sql=false"
    DATABASE_ID: "odev"
    HEALTHCHECK_QUERY: "select 1 from dual"
    SAVE_DB: "true"
  secretProvider:
    !!merge <<: *azureSecretProvider
    envSecrets:
      !!merge <<: *envSecret
      DB_CONFIG_PASSWORD: "oracle-db-cfg-dev-password"
oracleprod:
  !!merge <<: *basecache
  image:
    repository: pagopadcommonacr.azurecr.io/pagopaapiconfigcache
    tag: "0.5.0-nocolumns"
  ingress:
    !!merge <<: *ingress
    path: /api-config-cachedev/oprod(/|$)(.*)
  envConfig:
    !!merge <<: *envConfig
    APPLICATIONINSIGHTS_ROLE_NAME: "pagopa-api-config-cache-oracle"
    DB_CONFIG_URL: "jdbc:oracle:thin:@db-nodo-pagamenti.d.db-nodo-pagamenti.com:1522/NDPSPCT_NODO4_CFG"
    DB_CONFIG_USER: "NODO4_CFG_EXPORT"
    DB_CONFIG_DRIVER: "oracle.jdbc.OracleDriver"
    JAVA_OPTS: "-Dspring.jpa.show-sql=false"
    DATABASE_ID: "oprod"
    HEALTHCHECK_QUERY: "select 1 from dual"
    SAVE_DB: "true"
  secretProvider:
    !!merge <<: *azureSecretProvider
    envSecrets:
      !!merge <<: *envSecret
      DB_CONFIG_PASSWORD: "oracle-db-cfg-prod-password"
