/'
Scenario 04:
  Node retrieves last cache version id, but it is not present on Redis
'/
@startuml
participant Node
participant APIM
participant "API Config\nCache" as Cache

Node -> APIM: <b>/stakeholders/node/cache/schemas/v1/id</b>
APIM -> Cache: <b>/stakeholders/node/cache/schemas/v1/id</b>
Cache -x Redis: Get <b>apicfg_p_node_v1_id</b>
Cache --> APIM: <i>404 CACHE_NOT_INITIALIZED</i>
APIM --> Node: <i>404 CACHE_NOT_INITIALIZED</i>
@enduml
