/'
Scenario 05:
  Stakeholder (e.g. API-Config, SelfCare) refreshes cache data
'/
@startuml
Stakeholder -> APIM: <b>/stakeholders/node/cache/schemas/v1?refresh=true</b>
APIM -> APIM: Check <b>refresh</b> is required
APIM -> "API Config\nCache": <b>/stakeholders/node/cache/schemas/v1
"API Config\nCache" -> Redis: Save cache data with key <b>apicfg_*_node_v1</b>
"API Config\nCache" -> Redis: Save cache version with key <b>apicfg_*_node_v1_id</b>
note right
  <b>*</b> regards the database version (o or p)
end note
"API Config\nCache" --> APIM: Return cache data
APIM [#ff0000]--> Redis: Save cache data
note right
  this is a necessary workaround to allow APIM to read cache on Redis
end note
@enduml
