/'
Scenario 03:
  Node retrieves last cache version id
'/
@startuml
Node -> APIM: <b>/stakeholders/node/cache/schemas/v1/id</b>
APIM -> "API Config\nCache": <b>/stakeholders/node/cache/schemas/v1/id</b>
"API Config\nCache" -> Redis: Get <b>apicfg_*_node_v1_id
note right
  <b>*</b> regards the database version (o or p)
end note
Redis --> "API Config\nCache": Return version id
"API Config\nCache" --> APIM: Return version id
APIM --> Node: Return version id
@enduml
