/'
Scenario 02:
  Node retrieves cache, and it is present on Redis
'/
@startuml
participant Node
participant APIM
participant "API Config\nCache" as Cache
Node -> APIM: /stakeholders/node/cache/schemas/v1
APIM -> Cache: /stakeholders/node/cache/schemas/v1
Cache -> Redis: Check <b>apicfg_*_node_v1</b> exists
note right
  <b>*</b> regards the database version (o or p)
end note
Redis --> Cache: Return cache data
Cache --> APIM: Return cache data
APIM --> Node: Return cache data
@enduml
