/'
Scenario 01:
  Node retrieves cache and no cache is present on Redis
'/
@startuml
Node -> APIM: <b>/stakeholders/node/cache/schemas/v1</b>
APIM -> Redis: Check <b>apicfg_*_node_v1</b> exists
note right
  <b>*</b> regards the database version (o or p)
end note
Redis --> APIM: No cache found
APIM -> "API Config\nCache": <b>/stakeholders/node/cache/schemas/v1
"API Config\nCache" -> Redis: Save cache data with key <b>apicfg_*_node_v1</b>
note right
  <b>*</b> regards the database version (o or p)
end note
"API Config\nCache" --> APIM: Return cache data
APIM --> Node: Return cache data
@enduml
