/'
Scenario 03:
  Node retrieves last cache version id
'/
@startuml
participant Node
participant APIM
participant "API Config\nCache" as Cache
Node -> APIM: <b>/stakeholders/node/cache/schemas/v1/id</b>
APIM -> Cache: <b>/stakeholders/node/cache/schemas/v1/id</b>
Cache -> Redis: Get <b>apicfg_p_node_v1_id</b>
Cache --> APIM: Return version id
APIM --> Node: Return version id
@enduml
