apiVersion: v2
name: pagopa-api-cache-chart
description: Microservice that handles calculation for pagoPA Advanced Fees Management
type: application
version: 0.36.0
dependencies:
  - name: microservice-chart
    version: 3.0.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: postgresql
    condition: postgresql.enabled
  - name: microservice-chart
    version: 3.0.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: oracle
    condition: oracle.enabled
  - name: microservice-chart
    version: 3.0.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: oracledev
    condition: oracledev.enabled
  - name: microservice-chart
    version: 3.0.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: oracleprod
    condition: oracleprod.enabled
  - name: cron-chart
    version: 2.3.0
    repository: "https://pagopa.github.io/aks-cron-chart-blueprint"
    alias: refresh-p
  - name: cron-chart
    version: 2.3.0
    repository: "https://pagopa.github.io/aks-cron-chart-blueprint"
    alias: refresh-o
  - name: cron-chart
    version: 2.3.0
    repository: "https://pagopa.github.io/aks-cron-chart-blueprint"
    alias: refresh-odev
  - name: cron-chart
    version: 2.3.0
    repository: "https://pagopa.github.io/aks-cron-chart-blueprint"
    alias: refresh-oprod
appVersion: 0.8.11-2-NOD-742_cache_memory
