apiVersion: v2
name: pagopa-api-cache-chart
description: Microservice that handles calculation for pagoPA Advanced Fees Management
type: application
version: 0.48.0
dependencies:
  - name: microservice-chart
    version: 3.0.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: postgresql
    condition: postgresql.enabled
  - name: microservice-chart
    version: 3.0.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: oracle
    condition: oracle.enabled
  - name: microservice-chart
    version: 3.0.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: oracledev
    condition: oracledev.enabled
  - name: microservice-chart
    version: 3.0.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: oracleprod
    condition: oracleprod.enabled
  - name: cron-chart
    version: 2.3.0
    repository: "https://pagopa.github.io/aks-cron-chart-blueprint"
    alias: refresh-p
    condition: postgresql.enabled
  - name: cron-chart
    version: 2.3.0
    repository: "https://pagopa.github.io/aks-cron-chart-blueprint"
    alias: refresh-o
    condition: oracle.enabled
  - name: cron-chart
    version: 2.3.0
    repository: "https://pagopa.github.io/aks-cron-chart-blueprint"
    alias: refresh-odev
    condition: oracledev.enabled
  - name: cron-chart
    version: 2.3.0
    repository: "https://pagopa.github.io/aks-cron-chart-blueprint"
    alias: refresh-oprod
    condition: oracleprod.enabled
appVersion: 0.8.17-6-get_cache_by_keys
