apiVersion: v2
name: pagopa-api-cache-chart
description: Microservice that handles calculation for pagoPA Advanced Fees Management
type: application
version: 0.67.0
dependencies:
  ##############
  ## POSTGRES ##
  ## PAGOPA   ##
  ##############
  - name: microservice-chart
    version: 3.0.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: postgresql # postgres pagopa
    condition: postgresql.enabled
  - name: microservice-chart
    version: 3.0.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: postgresql-replica # postgres pagopa
    condition: postgresql-replica.enabled
  # CRON
  - name: cron-chart
    version: 2.6.0
    repository: "https://pagopa.github.io/aks-cron-chart-blueprint"
    alias: refresh-p # postgres pagopa
    condition: postgresql.enabled
  - name: cron-chart
    version: 2.6.0
    repository: "https://pagopa.github.io/aks-cron-chart-blueprint"
    alias: refresh-p-replica # postgres pagopa
    condition: postgresql-replica.enabled
  ##############
  ## ORACLE   ##
  ## NEXI     ##
  ##############
  - name: microservice-chart
    version: 3.0.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: oracle # oracle nexi (sit, uat, prod)
    condition: oracle.enabled
  - name: microservice-chart
    version: 3.0.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: oracledev # oracle nexi (dev o prf)
    condition: oracledev.enabled
  - name: microservice-chart
    version: 3.0.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: oracleprod # oracle nexi (prod in dev per test)
    condition: oracleprod.enabled
  # CRON
  - name: cron-chart
    version: 2.6.0
    repository: "https://pagopa.github.io/aks-cron-chart-blueprint"
    alias: refresh-o # oracle nexi (sit, uat, prod)
    condition: oracle.enabled
  - name: cron-chart
    version: 2.6.0
    repository: "https://pagopa.github.io/aks-cron-chart-blueprint"
    alias: refresh-odev # oracle nexi (dev o prf)
    condition: oracledev.enabled
  - name: cron-chart
    version: 2.6.0
    repository: "https://pagopa.github.io/aks-cron-chart-blueprint"
    alias: refresh-oprod # oracle nexi (prod in dev per test)
    condition: oracleprod.enabled
  ##############
  ## POSTGRES ##
  ## NEXI     ##
  ##############
  - name: microservice-chart
    version: 3.0.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: postgresql-nexi # postgres nexi
    condition: postgresql-nexi.enabled
  - name: cron-chart
    version: 2.6.0
    repository: "https://pagopa.github.io/aks-cron-chart-blueprint"
    alias: refresh-p-nexi # postgres nexi
    condition: postgresql-nexi.enabled
  - name: microservice-chart
    version: 3.0.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: postgresql-replica-nexi # postgres prf nexi
    condition: postgresql-replica-nexi.enabled
  - name: cron-chart
    version: 2.6.0
    repository: "https://pagopa.github.io/aks-cron-chart-blueprint"
    alias: refresh-p-replica-nexi # postgres prf nexi
    condition: postgresql-replica-nexi.enabled
appVersion: 0.9.7-2-NOD-855-deploy-dev
