apiVersion: v2
name: pagopa-api-cache-chart
description: Microservice that handles calculation for pagoPA Advanced Fees Management
type: application
version: 0.0.1
dependencies:
  - name: postgresql
    version: 3.0.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    condition: postgresql.enabled
  - name: oracle
    version: 3.0.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    condition: oracle.enabled
