microservice-chart: &microservice-chart
  namespace: "apiconfig"
  image:
    repository: ghcr.io/pagopa/pagopa-api-config-cache
    tag: 0.8.4
  canaryDelivery:
    deployment:
      image:
        repository: ghcr.io/pagopa/pagopa-api-config-cache
        tag: 0.8.0
    create: false
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 30
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 30
  ingress: &ingress
    create: true
    host: "weuprod.apiconfig.internal.platform.pagopa.it"
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.25"
    limits:
      memory: "6G"
      cpu: "2.5"
  envConfig: &envConfig
    ENV: "prod"
    AZURE_INSIGHTS_ENABLED: "true"
    REDIS_HOST: "pagopa-p-redis.redis.cache.windows.net"
    REDIS_PORT: "6380"
    OTEL_SERVICE_NAME: "pagopa-api-config-cache"
    OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=azure-prod"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-system.svc:4317"
    OTEL_LOGS_EXPORTER: none
    OTEL_TRACES_SAMPLER: "always_on"
  secretProvider: &azureSecretProvider
    create: true
    envSecrets: &envSecret
      APPLICATIONINSIGHTS_CONNECTION_STRING: "ai-p-connection-string"
      REDIS_PWD: "redis-password"
      OTEL_EXPORTER_OTLP_HEADERS: elastic-apm-secret-token
    keyvault:
      name: "pagopa-p-apiconfig-kv"
      tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  tmpVolumeMount:
    create: true
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/instance: "pagopa-api-config-cache-postgresql"
            namespaces: [ "apiconfig" ]
            topologyKey: topology.kubernetes.io/zone
# Configuration used to update image tag
postgresql:
  !!merge <<: *microservice-chart
  ingress:
    !!merge <<: *ingress
    path: /api-config-cache/p(/|$)(.*)
  envConfig:
    !!merge <<: *envConfig
    APPLICATIONINSIGHTS_ROLE_NAME: "pagopa-api-config-cache-postgresql"
    DB_CONFIG_URL: "jdbc:postgresql://nodo-db.p.internal.postgresql.pagopa.it:6432/nodo?sslmode=require&prepareThreshold=0&currentSchema=cfg"
    DB_CONFIG_USER: "cfg"
    DB_CONFIG_DRIVER: "org.postgresql.Driver"
    DATABASE_ID: "p"
    HEALTHCHECK_QUERY: "select 1"
  secretProvider:
    !!merge <<: *azureSecretProvider
    envSecrets:
      !!merge <<: *envSecret
      DB_CONFIG_PASSWORD: "postgresql-db-cfg-password"
oracle:
  !!merge <<: *microservice-chart
  ingress:
    !!merge <<: *ingress
    path: /api-config-cache/o(/|$)(.*)
  envConfig:
    !!merge <<: *envConfig
    APPLICATIONINSIGHTS_ROLE_NAME: "pagopa-api-config-cache-oracle"
    DB_CONFIG_URL: "jdbc:oracle:thin:@db-nodo-pagamenti.p.db-nodo-pagamenti.com:1521/NDPSPCP_NODO4_CFG"
    DB_CONFIG_USER: "NODO4_CFG"
    DB_CONFIG_DRIVER: "oracle.jdbc.OracleDriver"
    JAVA_OPTS: "-Dspring.jpa.show-sql=false -XX:MaxHeapSize=4g"
    DATABASE_ID: "o"
    IN_PROGRESS_TTL: "20"
    HEALTHCHECK_QUERY: "select 1 from dual"
    SAVE_DB: "true"
    DEFAULT_LOGGING_LEVEL: "info" # TODO remove
  secretProvider:
    !!merge <<: *azureSecretProvider
    envSecrets:
      !!merge <<: *envSecret
      DB_CONFIG_PASSWORD: "oracle-db-cfg-password"
oracledev:
  enabled: false
oracleprod:
  !!merge <<: *microservice-chart
  ingress:
    !!merge <<: *ingress
    path: /api-config-cachedev/oprod(/|$)(.*)
  envConfig:
    !!merge <<: *envConfig
    APPLICATIONINSIGHTS_ROLE_NAME: "pagopa-api-config-cache-oracle"
    DB_CONFIG_URL: "jdbc:oracle:thin:@(DESCRIPTION=(ENABLE=BROKEN)(ADDRESS=(PROTOCOL=tcp)(PORT=1521)(HOST=db-nodo-pagamenti.p.db-nodo-pagamenti.com))(CONNECT_DATA=(SERVICE_NAME=NDPSPCP_NODO4_CFG))(SO_KEEPALIVE=true)(TCP_KEEPIDLE=60)(TCP_KEEPINTVL=30)(TCP_KEEPCNT=15))"
    DB_CONFIG_USER: "NODO4_CFG"
    DB_CONFIG_DRIVER: "oracle.jdbc.OracleDriver"
    JAVA_OPTS: "-Dspring.jpa.show-sql=false"
    DATABASE_ID: "oprod"
    IN_PROGRESS_TTL: "20"
    HEALTHCHECK_QUERY: "select 1 from dual"
    SAVE_DB: "true"
  secretProvider:
    !!merge <<: *azureSecretProvider
    envSecrets:
      !!merge <<: *envSecret
      DB_CONFIG_PASSWORD: "oracle-db-cfg-password"
