microservice-chart: &microservice-chart
  namespace: "apiconfig"
  image:
    repository: ghcr.io/pagopa/pagopa-api-config-cache
    tag: 0.9.35
  canaryDelivery:
    deployment:
      image:
        repository: ghcr.io/pagopa/pagopa-api-config-cache
        tag: 0.8.0
    create: false
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 90
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 90
  ingress: &ingress
    create: true
    host: "weuuat.apiconfig.internal.uat.platform.pagopa.it"
  serviceAccount:
    name: "apiconfig-workload-identity"
  azure:
    workloadIdentityClientId: <workload-identity-client-id-set-automatically-by-gha>
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.25"
    limits:
      memory: "2G"
      cpu: "1"
  envConfig: &envConfig
    ENV: "uat"
    TZ: "Europe/Rome"
    AZURE_INSIGHTS_ENABLED: "true"
    REDIS_PORT: "6380"
    OTEL_SERVICE_NAME: "pagopa-api-config-cache"
    OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=azure-uat"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-system.svc:4317"
    OTEL_LOGS_EXPORTER: none
    OTEL_TRACES_SAMPLER: "always_on"
    CACHET_TX_NAME: "nodo-dei-pagamenti-cache"
  envSecret: &envSecret
    APPLICATIONINSIGHTS_CONNECTION_STRING: "ai-u-connection-string"
    REDIS_PWD: "redis-password"
    REDIS_HOST: "redis-hostname"
    OTEL_EXPORTER_OTLP_HEADERS: elastic-apm-secret-token
    CACHE_TX_CONNECTION_STRING: "nodo-dei-pagamenti-cache-tx-connection-string-key"
  keyvault:
    name: "pagopa-u-apiconfig-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  tmpVolumeMount:
    create: true
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
# Configuration used to update image tag
##############
## SERVICES ##
##############
# postgres pagopa - UAT
postgresql:
  !!merge <<: *microservice-chart
  ingress:
    !!merge <<: *ingress
    path: /api-config-cache/p/(.*)
  envConfig:
    !!merge <<: *envConfig
    APPLICATIONINSIGHTS_ROLE_NAME: "pagopa-api-config-cache-postgresql"
    DB_CONFIG_URL: "jdbc:postgresql://nodo-db.u.internal.postgresql.pagopa.it:5432/nodo?sslmode=require&prepareThreshold=0&currentSchema=cfg"
    DB_CONFIG_USER: "cfg"
    DB_CONFIG_DRIVER: "org.postgresql.Driver"
    DATABASE_ID: "p"
    HEALTHCHECK_QUERY: "select 1"
    SAVE_DB: "false"
    SEND_EVENT: "true"
  envSecret:
    !!merge <<: *envSecret
    DB_CONFIG_PASSWORD: "postgresql-db-cfg-password"
# postgres pagopa - PRF
postgresql-replica:
  enabled: false
#  !!merge <<: *microservice-chart
#  ingress:
#    !!merge <<: *ingress
#    path: /api-config-cache/pr/(.*)
#  envConfig:
#    !!merge <<: *envConfig
#    APPLICATIONINSIGHTS_ROLE_NAME: "pagopa-api-config-cache-postgresql-replica"
#    DB_CONFIG_URL: "jdbc:postgresql://nodo-perf-db.u.internal.postgresql.pagopa.it:6432/nodo-replica?sslmode=require&prepareThreshold=0&currentSchema=cfg"
#    DB_CONFIG_USER: "cfg"
#    DB_CONFIG_DRIVER: "org.postgresql.Driver"
#    DATABASE_ID: "pr"
#    HEALTHCHECK_QUERY: "select 1"
#    SAVE_DB: "false"
#    SEND_EVENT: "false"
#  envSecret:
#    !!merge <<: *envSecret
#    DB_CONFIG_PASSWORD: "postgresql-db-cfg-password"
# postgres nexi - UAT
postgresql-nexi:
  enabled: false
#  !!merge <<: *microservice-chart
#  ingress:
#    !!merge <<: *ingress
#    path: /api-config-cache/nexi/p/(.*)
#  envConfig:
#    !!merge <<: *envConfig
#    APPLICATIONINSIGHTS_ROLE_NAME: "pagopa-api-config-cache-postgresql-nexi"
#    DB_CONFIG_URL: "jdbc:postgresql://db-postgres-ndp.u.db-nodo-pagamenti.com:5445/ndpspca?prepareThreshold=0&currentSchema=NODO4_CFG"
#    DB_CONFIG_USER: "pp_nodo4_cfg"
#    DB_CONFIG_DRIVER: "org.postgresql.Driver"
#    DATABASE_ID: "pnexi"
#    HEALTHCHECK_QUERY: "select 1"
#    SAVE_DB: "true"
#    SEND_EVENT: "false"
#  envSecret:
#    !!merge <<: *envSecret
#    DB_CONFIG_PASSWORD: "db-postgres-nexi-cfg-password"
# postgres nexi - PRF
postgresql-replica-nexi:
  enabled: false
#  !!merge <<: *microservice-chart
#  ingress:
#    !!merge <<: *ingress
#    path: /api-config-cache/nexi/pr/(.*)
#  envConfig:
#    !!merge <<: *envConfig
#    APPLICATIONINSIGHTS_ROLE_NAME: "pagopa-api-config-cache-postgresql-replica-nexi"
#    #DB_CONFIG_URL: "jdbc:postgresql://db-postgres-ndp-prf.u.db-nodo-pagamenti.com:5444/ndpspcq?prepareThreshold=0&currentSchema=NODO4_CFG" # OK!
#    DB_CONFIG_URL: "jdbc:postgresql://db-postgres-ndp-prf-1.u.db-nodo-pagamenti.com:6432,db-postgres-ndp-prf-2.u.db-nodo-pagamenti.com:6432/ndpspcq"
#    #DB_CONFIG_URL: "jdbc:postgresql://db-postgres-ndp-prf-1.u.db-nodo-pagamenti.com:6432/ndpspcq"
#    DB_CONFIG_USER: "pp_nodo4_cfg"
#    #    DB_CONFIG_USER: "nodo4_cfg"
#    DB_CONFIG_DRIVER: "org.postgresql.Driver"
#    DATABASE_ID: "prnexi"
#    ENV: "prf"
#    HEALTHCHECK_QUERY: "select 1"
#    SAVE_DB: "true"
#    SEND_EVENT: "false"
#  envSecret:
#    !!merge <<: *envSecret
#    DB_CONFIG_PASSWORD: "db-postgres-nexi-cfg-password-prf"
# oracle nexi - UAT
oracle:
  enabled: false
#  !!merge <<: *microservice-chart
#  ingress:
#    !!merge <<: *ingress
#    path: /api-config-cache/o(/|$)(.*)
#  envConfig:
#    !!merge <<: *envConfig
#    APPLICATIONINSIGHTS_ROLE_NAME: "pagopa-api-config-cache-oracle"
#    DB_CONFIG_URL: "jdbc:oracle:thin:@(DESCRIPTION=(ENABLE=BROKEN)(ADDRESS=(PROTOCOL=tcp)(PORT=1524)(HOST=db-nodo-pagamenti.u.db-nodo-pagamenti.com))(CONNECT_DATA=(SERVICE_NAME=NDPSPCA_NODO4_CFG))(SO_KEEPALIVE=true)(TCP_KEEPIDLE=60)(TCP_KEEPINTVL=30)(TCP_KEEPCNT=15))"
#    DB_CONFIG_USER: "NODO4_CFG"
#    DB_CONFIG_DRIVER: "oracle.jdbc.OracleDriver"
#    DATABASE_ID: "o"
#    HEALTHCHECK_QUERY: "select 1 from dual"
#    SAVE_DB: "false"
#    SEND_EVENT: "false"
#  secretProvider:
#    !!merge <<: *azureSecretProvider
#    envSecrets:
#      !!merge <<: *envSecret
#      DB_CONFIG_PASSWORD: "oracle-db-cfg-password-tmp"
# oracle nexi - DEV
oracledev:
  enabled: false
#  !!merge <<: *microservice-chart
#  ingress:
#    !!merge <<: *ingress
#    path: /api-config-cachedev/o(/|$)(.*)
#  envConfig:
#    !!merge <<: *envConfig
#    DB_CONFIG_URL: "jdbc:oracle:thin:@(DESCRIPTION=(ENABLE=BROKEN)(ADDRESS=(PROTOCOL=tcp)(PORT=1524)(HOST=db-nodo-pagamenti-prf.u.db-nodo-pagamenti.com))(CONNECT_DATA=(SERVICE_NAME=NDPSPCST_NODO4_CFG))(SO_KEEPALIVE=true)(TCP_KEEPIDLE=60)(TCP_KEEPINTVL=30)(TCP_KEEPCNT=15))"
#    DB_CONFIG_USER: "NODO4_CFG"
#    DB_CONFIG_DRIVER: "oracle.jdbc.OracleDriver"
#    DATABASE_ID: "odev"
#    HEALTHCHECK_QUERY: "select 1 from dual"
#    SAVE_DB: "true"
#    SEND_EVENT: "false"
#  secretProvider:
#    !!merge <<: *azureSecretProvider
#    envSecrets:
#      !!merge <<: *envSecret
#      DB_CONFIG_PASSWORD: "oracle-db-cfg-prf-password"
# oracle nexi - PROD x TEST
oracleprod:
  enabled: false
#############
## REFRESH ##
#############
# postgres pagopa - DEV
refresh-p:
  namespace: "apiconfig"
  schedule: "0 0 * * *"
  timeZone: "Europe/Rome"
  successfulJobsHistoryLimit: "1"
  image:
    repository: "curlimages/curl"
    tag: "latest"
    pullPolicy: "Always"
  command:
    - "curl"
    - "-k"
    - "-m"
    - "\"300\""
    - "--header"
    - "\"Ocp-Apim-Subscription-Key: $(API_CONFIG_CACHE_SUBSCRIPTION_KEY)\""
    - "https://api.uat.platform.pagopa.it/api-config-cache/p/v1/cache/refresh"
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "150m"
  envSecrets:
    !!merge <<: *envSecret
    API_CONFIG_CACHE_SUBSCRIPTION_KEY: "cfg-for-node-subscription-key"
  keyvault:
    name: "pagopa-u-apiconfig-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  serviceAccount:
    name: "apiconfig-workload-identity"
  tolerations:
    - key: dedicated
      operator: Equal
      value: "apiconfig"
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
# postgres pagopa - IT
refresh-p-replica:
  enabled: false
#  namespace: "apiconfig"
#  schedule: "0 0 * * *"
#  timeZone: "Europe/Rome"
#  successfulJobsHistoryLimit: "1"
#  image:
#    repository: "curlimages/curl"
#    tag: "latest"
#    pullPolicy: "Always"
#  command:
#    - "curl"
#    - "-k"
#    - "-m"
#    - "\"300\""
#    - "--header"
#    - "\"Ocp-Apim-Subscription-Key: $(API_CONFIG_CACHE_SUBSCRIPTION_KEY)\""
#    - "https://api.uat.platform.pagopa.it/api-config-cache/pr/v1/cache/refresh"
#  resources:
#    requests:
#      memory: "256Mi"
#      cpu: "100m"
#    limits:
#      memory: "512Mi"
#      cpu: "150m"
#  envSecrets:
#    !!merge <<: *envSecret
#    API_CONFIG_CACHE_SUBSCRIPTION_KEY: "cfg-for-node-subscription-key"
#  keyvault:
#    name: "pagopa-u-apiconfig-kv"
#    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
#  serviceAccount:
#    name: "apiconfig-workload-identity"
#  tolerations:
#    - key: dedicated
#      operator: Equal
#      value: "apiconfig"
#      effect: NoSchedule
#  affinity:
#    nodeAffinity:
#      requiredDuringSchedulingIgnoredDuringExecution:
#        nodeSelectorTerms:
#          - matchExpressions:
#              - key: node_type
#                operator: In
#                values:
#                  - user
# postgres nexi - UAT
refresh-p-nexi:
  enabled: false
#  namespace: "apiconfig"
#  schedule: "0 0 * * *"
#  timeZone: "Europe/Rome"
#  successfulJobsHistoryLimit: "1"
#  image:
#    repository: "curlimages/curl"
#    tag: "latest"
#    pullPolicy: "Always"
#  command:
#    - "curl"
#    - "-k"
#    - "-m"
#    - "\"300\""
#    - "--header"
#    - "\"Ocp-Apim-Subscription-Key: $(API_CONFIG_CACHE_SUBSCRIPTION_KEY)\""
#    - "https://api.uat.platform.pagopa.it/api-config-cache/nexi/p/v1/cache/refresh"
#  resources:
#    requests:
#      memory: "256Mi"
#      cpu: "100m"
#    limits:
#      memory: "512Mi"
#      cpu: "150m"
#  envSecrets:
#    !!merge <<: *envSecret
#    API_CONFIG_CACHE_SUBSCRIPTION_KEY: "cfg-for-node-subscription-key"
#  keyvault:
#    name: "pagopa-u-apiconfig-kv"
#    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
#  serviceAccount:
#    name: "apiconfig-workload-identity"
#  tolerations:
#    - key: dedicated
#      operator: Equal
#      value: "apiconfig"
#      effect: NoSchedule
#  affinity:
#    nodeAffinity:
#      requiredDuringSchedulingIgnoredDuringExecution:
#        nodeSelectorTerms:
#          - matchExpressions:
#              - key: node_type
#                operator: In
#                values:
#                  - user
# postgres nexi - PRF
refresh-p-replica-nexi:
  namespace: "apiconfig"
  schedule: "0 0 * * *"
  timeZone: "Europe/Rome"
  successfulJobsHistoryLimit: "1"
  image:
    repository: "curlimages/curl"
    tag: "latest"
    pullPolicy: "Always"
  command:
    - "curl"
    - "-k"
    - "-m"
    - "\"300\""
    - "--header"
    - "\"Ocp-Apim-Subscription-Key: $(API_CONFIG_CACHE_SUBSCRIPTION_KEY)\""
    - "https://api.uat.platform.pagopa.it/api-config-cache/nexi/pr/v1/cache/refresh"
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "150m"
  envSecrets:
    !!merge <<: *envSecret
    API_CONFIG_CACHE_SUBSCRIPTION_KEY: "cfg-for-node-subscription-key"
  keyvault:
    name: "pagopa-u-apiconfig-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  serviceAccount:
    name: "apiconfig-workload-identity"
  tolerations:
    - key: dedicated
      operator: Equal
      value: "apiconfig"
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
# oracle nexi - SIT
refresh-o:
  enabled: false
#  namespace: "apiconfig"
#  schedule: "0 0 * * *"
#  timeZone: "Europe/Rome"
#  successfulJobsHistoryLimit: "1"
#  image:
#    repository: "curlimages/curl"
#    tag: "latest"
#    pullPolicy: "Always"
#  command:
#    - "curl"
#    - "-k"
#    - "-m"
#    - "\"300\""
#    - "--header"
#    - "\"Ocp-Apim-Subscription-Key: $(API_CONFIG_CACHE_SUBSCRIPTION_KEY)\""
#    - "https://api.uat.platform.pagopa.it/api-config-cache/o/v1/cache/refresh"
#  resources:
#    requests:
#      memory: "256Mi"
#      cpu: "100m"
#    limits:
#      memory: "512Mi"
#      cpu: "150m"
#  secretProvider:
#    !!merge <<: *azureSecretProvider
#    envSecrets:
#      !!merge <<: *envSecret
#      API_CONFIG_CACHE_SUBSCRIPTION_KEY: "cfg-for-node-subscription-key"
#  tolerations:
#    - key: dedicated
#      operator: Equal
#      value: "apiconfig"
#      effect: NoSchedule
#  affinity:
#    nodeAffinity:
#      requiredDuringSchedulingIgnoredDuringExecution:
#        nodeSelectorTerms:
#          - matchExpressions:
#              - key: node_type
#                operator: In
#                values:
#                  - user
# oracle nexi - DEV
refresh-odev:
  enabled: false
#  namespace: "apiconfig"
#  schedule: "0 0 * * *"
#  timeZone: "Europe/Rome"
#  successfulJobsHistoryLimit: "1"
#  image:
#    repository: "curlimages/curl"
#    tag: "latest"
#    pullPolicy: "Always"
#  command:
#    - "curl"
#    - "-k"
#    - "-m"
#    - "\"300\""
#    - "--header"
#    - "\"Ocp-Apim-Subscription-Key: $(API_CONFIG_CACHE_SUBSCRIPTION_KEY)\""
#    - "https://api.uat.platform.pagopa.it/api-config-cache/or/v1/cache/refresh"
#  resources:
#    requests:
#      memory: "256Mi"
#      cpu: "100m"
#    limits:
#      memory: "512Mi"
#      cpu: "150m"
#  secretProvider:
#    !!merge <<: *azureSecretProvider
#    envSecrets:
#      !!merge <<: *envSecret
#      API_CONFIG_CACHE_SUBSCRIPTION_KEY: "cfg-for-node-subscription-key"
#  tolerations:
#    - key: dedicated
#      operator: Equal
#      value: "apiconfig"
#      effect: NoSchedule
#  affinity:
#    nodeAffinity:
#      requiredDuringSchedulingIgnoredDuringExecution:
#        nodeSelectorTerms:
#          - matchExpressions:
#              - key: node_type
#                operator: In
#                values:
#                  - user
# oracle nexi - PROD x TEST
refresh-oprod:
  enabled: false
